// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpxsOAg9BV_661TFnAfy7nlXb4IkzTCnA',
    appId: '1:562455088953:android:2196d03f9cb43fdf51a2e8',
    messagingSenderId: '562455088953',
    projectId: 'project-e8203',
    databaseURL: 'https://project-e8203-default-rtdb.firebaseio.com',
    storageBucket: 'project-e8203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrEU0srpqaC_J1psHmYu3UM3uItVWNkE',
    appId: '1:562455088953:ios:8efd8dd41cb0f7cc51a2e8',
    messagingSenderId: '562455088953',
    projectId: 'project-e8203',
    databaseURL: 'https://project-e8203-default-rtdb.firebaseio.com',
    storageBucket: 'project-e8203.appspot.com',
    iosClientId: '562455088953-sq4u3tmrjpj6o9dfhqbijdl7420r8mth.apps.googleusercontent.com',
    iosBundleId: 'com.example.priject3',
  );
}
